# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'v0.*'
      - 'v1.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Build
      run: CGO_ENABLED=0 go build -v ./...
    
    - name: Publish binary
      run: curl --user AnsibleContainerOCIPublisher:y${{ secrets.ANSIBLECONTAINEROCIPUBLISHERPASSWORD }} \
     --upload-file ./http-multicaster \
     https://git.zd-est.pref.gouv.fr/api/packages/SGAMI-EST/generic/http-multicaster/${{ gitea.ref_name }}/http-multicaster-amd64
