name: Build and Publish Go Binary

on:
  push:
    branches:
      - PublisherWorkflow  # Trigger on push to the main branch
    tags:
      - v*    # Trigger on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.2'  # Specify the Go version

    - name: Build Go binary
      env:
        CGO_ENABLED: 0 
      run: |
        go build

    - name: Publish to Gitea Generic Package Repository
      env:
        GITEA_TOKEN: ${{ secrets.GITEATOKEN }}  # Ensure you have a GITEA_TOKEN secret set up
      run: |
        curl -X PUT \
          -H "Authorization: token $GITEA_TOKEN" \
          -F "data=@./dist/http-multicaster" \
          "https://git.zd-est.pref.gouv.fr/api/packages/sgami-est/generic/http-multicaster/${{ github.ref_name }}/http-multicaster-${{ github.ref_name }}"
